spring.application.name=demo

# Configuracoes comuns entre perfis
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

# Logs para depuracao das rotas da aplicacao
logging.level.com.estudo.npi.demo=DEBUG
logging.level.org.springframework.web=INFO
