CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    preco DOUBLE PRECISION,
    categoria VARCHAR(50)
);

DROP table PRODUTO;


select * from produto;